#heterozygosity disteribution per site across genome
#the raw files are generated by first converting VCF files to plink files, and then rewriting plink bed files to plink raw files (using plink command --recodeA)

library(data.table)
all_num_hets = c()
for(CHR in 1:21){
	if(CHR > 1){
		F = fread(paste("chr",CHR,"raw.raw",sep=""),stringsAsFactors=FALSE,data.table=FALSE,skip=1)
	}else{
		F = fread("temp",stringsAsFactors=FALSE,data.table=FALSE,header=FALSE)
	}
	F = F[,-c(1:6)]
	num_hets = apply(F,2,function(x){length(which(x == 1))})
	all_num_hets = c(all_num_hets, num_hets)
}

points = c(7.2,7.2,6.9,6.4,5.6,4.7,3.5,2.1,0.37)
pdf("figure2.pdf")
 a = barplot(log10(table(all_num_hets)),main="",ylab="log10 count of 9 classes", xlab="Class of heterozygous calls defined by the number of lines it appeared in",ylim=c(0,7.35))
 points(a[,1], y=points,pch=19)
dev.off()

